### ISSUE TITLE
Data from WDIcache not effective in WDI

### ISSUE THREAD

**Issue by pssguy** [vincentarelbundock/WDI#19]
According to the documentation, `WDIcache()` returns a data frame

I actually get a list back but created a data.frame, latestInfo

However, when I use the data in `WDI` I get mixed results

```
choice <- latestInfo$indicator[1] # "1.0.HCount.1.25usd"

data <- WDI(country = "all", 
       indicator = choice, 
       start = 1980, 
       end = 2015)
```

works but with this as input

```
choice <- latestInfo$indicator[10000] # "per_si_allsi.avt_q4_rur"
Warning message:
In WDI(country = "all", indicator = choice, start = 1980, end = 2015) :
Unable to download indicators  persiallsi.avtq4rur
```

**Comment by vincentarelbundock** [comment]
At some point a while ago I asked on the World Bank forum if there was a way to get a list of indicators that were *not* available. I didn't get anything conclusive back. Some indicators are listed when the API returns the list of data series, but do not seem to be available (through the API) for download. Since I can't know for sure, ex ante, which are available and which are not, I don't see an easy solution.

There was also a pretty major issue with over-aggressive cleaning of user input that was fixed a while ago, so it might be worth installing the github version of WDI to see if that solves your problem.

**Comment by vincentarelbundock** [comment]
9425bfd modifies the docs to specify that WDIcache returns a list.
