### ISSUE TITLE
Regions trailing spaces

### ISSUE THREAD

**Issue by EvaMaeRey** [vincentarelbundock/WDI#33]
Hi Vincent. I've been using your WDI package in my classes.  I've found that sometimes the regions for countries (extra = T) have trailing spaces.  This was the source of a bit of confusion in two cases for my students. One example is in subsetting with a Boolean (region == "Latin America ...")).  If you don't include the trailing space, then no rows are returned.  Do you think that you could do a cleaning step (str_trim()) for regions?  Great package!

**Comment by vincentarelbundock** [comment]
Thanks for the report.

Trying to be open about this: A couple years ago, some guy created a package with essentially the same functionality as WDI, called `wbstats`. I was a bit annoyed at first, as there didn't seem to be added value, but now it has a couple additional things that WDI can't do (yet).

About a month ago I got another request for improvement, which I punted on because duplication of efforts is blah... So I was thinking about deprecating, or making WDI a wrapper around his package, or just leaving this as-is. However, `wbstats` guy doesn't seem super responsive (some issues are super old on github)

Honestly, i don't quite know what to do, but effort duplication seems dumb...

Have you tried the other package? What do you think?

(sorry, I know you didn't come here for a psychoanalysis)

**Comment by vincentarelbundock** [comment]
https://github.com/vincentarelbundock/WDI/commit/63e3856b0168832b78643896b688ba7e744a0294

removes white space from the region identifiers.

now let's see if i can muster the courage for a cran release

**Comment by EvaMaeRey** [comment]
Thanks for this.  I had no idea there was another similar package!  So couldn't say how they compare.  Sorry to stir up old preoccupations!  Too bad about the repetition.

**Comment by vincentarelbundock** [comment]
Yeah, as far as I can tell, the only benefit of WDI is this:

https://github.com/vincentarelbundock/WDI#automatic-rename

**Comment by EvaMaeRey** [comment]
I'd be more likely to continue to advise using dplyr::rename() for rename (I didn't know about this functionality), honestly.  I might check out the other package, but I'm reluctant.  Would rather not update materials.  👍 for WDI.

**Comment by vincentarelbundock** [comment]
sounds good. I know some people use this, so I'm going to make sure it keeps working. Good luck with the class!

**Comment by EvaMaeRey** [comment]
👍

**Comment by EvaMaeRey** [comment]
Thanks!!!  I know other people who use it, too.
