### ISSUE TITLE
Country.Name

### ISSUE THREAD

**Issue by bangecon** [vincentarelbundock/WDI#34]
Maybe it's unique to me, but every time I run WDIbulk() there's an error reading Country.Name. It always reads as "ï..Country.Name". It's pretty easy to fix for myself, but was wondering if others have seen this issue and if there's a way to fix it short of just rewriting the function (and/or just writing your own code to download and unpack the indicators.

**Comment by Doelp** [comment]
I have the same issue. No solution, just wanted to mention that it is not unique to @bangecon

**Comment by jmxsy2016** [comment]
I have also the same issue.

**Comment by areckenrode** [comment]
I'm having the same issue, as well.

**Comment by vincentarelbundock** [comment]
Sorry I didn't check in earlier, but this has been resolved a while ago. Note that `WDIbulk` often times out because the World Bank website is slow and `R`'s `download.file` function has a default timeout of 60 seconds. The latest version on Github includes a `timeout` argument which solves this problem. To install:

```r
library(remotes)
install_github("vincentarelbundock/WDI")
```

Thanks for the report, and sorry for the delay.

**Comment by bangecon** [comment]
Thanks!
Jim
