### ISSUE TITLE
WDIbulk fails

### ISSUE THREAD

**Issue by geotheory** [vincentarelbundock/WDI#38]
Possibly related to the [other issue](https://github.com/vincentarelbundock/WDI/issues/37):

```
> x = WDIbulk()
trying URL 'https://databank.worldbank.org/data/download/WDI_csv.zip'
Content type 'application/x-zip-compressed' length 65341191 bytes (62.3 MB)
===========
downloaded 14.6 MB

Error in utils::download.file(url, temp) : 
  download from 'https://databank.worldbank.org/data/download/WDI_csv.zip' failed
In addition: Warning messages:
1: In utils::download.file(url, temp) :
  downloaded length 15286272 != reported length 65341191
2: In utils::download.file(url, temp) :
  URL 'https://databank.worldbank.org/data/download/WDI_csv.zip': status was 'Failure when receiving data from the peer'
```

**Comment by vincentarelbundock** [comment]
Thanks for the report. My intuition is that this is a different issue, since we are downloading a zipped CSV file, and not calling the API. 

I can replicate the error on my computer, so this is obviously a real problem.

I'm having issues just downloading the CSV file from Firefox though, so my hunch is that the WB server is at fault here.

Somethings these things soft themselves out eventually. Otherwise, we'll have to send a support request to the WB.

**Comment by vincentarelbundock** [comment]
The world bank website seems to be fixed. The current github master adds a `timeout` argument because this is a large file and the downloads often timed out.

Solved!

Sorry it took so long.
