### ISSUE TITLE
continue WDI development?

### ISSUE THREAD

**Issue by etiennebacher** [vincentarelbundock/WDI#45]
Hi Vincent,
I just stumbled upon [one of your comments](https://github.com/nset-ornl/wbstats/issues/10#issuecomment-460471954) on the `wbstats` package repo, which talks about deprecating `WDI` and orienting users towards `wbstats`. Since the comment was almost two years ago, I was wondering if this is still what you think you're gonna do, or if you will push new features to CRAN.
Personally, I discovered `WDI` before `wbstats` and I'd like to stick to it (unless there's a game changer feature in `wbstats`). 
I am also asking this because I'm thinking of adding new features to `WDI` (such as the World Bank [Projects API](http://search.worldbank.org/api/v2/projects)), unless you choose to deprecate the package.

**Comment by vincentarelbundock** [comment]
Good question. I just deleted the comment because it is no longer relevant. It took forever to implement the features mentioned in that thread, so I decided I would rather retain more control over the package to ensure that issues get resolved quickly.

TBH, I'm not sure I will personally invest a lot of time to add *new* features (I might do that; I just don't want to make promises). But I do plan to fix bugs and keep the package running.

Also, I'm more than happy to review and integrate PRs, especially when they are nice and clean like yours.

Releasing to CRAN is also quite easy, so I'm happy to do that semi-regular intervals. CRAN doesn't like it when we release more than every ~2 months, so it's important to let features accumulate a bit before releasing.

When we manage to ensure that all the current tests pass, and if you tell me that you have stopped looking at new possibilities, I'll play with the package a bit and see if we can prep a release.

**Comment by vincentarelbundock** [comment]
Also, I've been maintaining [another package since 2009](https://cran.r-project.org/src/contrib/Archive/countrycode/), and I believe strongly in the importance of long term support. So unless I get hit by a bus or something, it should be "safe" to make contributions to `WDI`.

**Comment by vincentarelbundock** [comment]
Finally, FYI, I just renamed the `master` branch to `main`.

**Comment by etiennebacher** [comment]
Hello, I just want to let you know that I won't work on implementing another World Bank API for now. I took a few hours to try to implement the WB Projects API, but it's more messy than the WDI one, and I don't know if it would really be useful. 

So feel free to submit to CRAN whenever you want (I don't close this issue as I think it might interest other people).

**Comment by vincentarelbundock** [comment]
cool. I just tried submitting a version. (I'm terrible at this and don't think I've ever succeed with a CRAN in one shot, but it'll get through eventually)

**Comment by etiennebacher** [comment]
Nice! By the way, if you don't already know it, here's a collaborative repo that lists the things to do before submitting to CRAN: https://github.com/ThinkR-open/prepare-for-cran

**Comment by vincentarelbundock** [comment]
This looks cool, thanks.

Perhaps my 10 years of package maintainable are starting pay off, because this one accepted on one shot :)
